// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIDataMetadata api data metadata
//
// swagger:model apiDataMetadata
type APIDataMetadata struct {

	// ts when the record was created
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

	// Who created the document, and who last wrote it.
	//
	// Two fields rather than one because writing an existing documentId is an
	// UPSERT: with only a creator, a document overwritten by a DIFFERENT
	// principal would still report the original author and the second write
	// would be invisible. "A created this, B replaced its contents" is the
	// question these exist to answer.
	//
	// _createdBy is set once, on insert, and never moves - it pairs with
	// _createdAt. _updatedBy is rewritten on every write, pairing with
	// _updatedAt. The two move independently for the same reason the two
	// timestamps do.
	//
	// EMPTY MEANS UNATTRIBUTED, not anonymous-and-fine. A deployment whose
	// caller resolver is not wired records no writer, and an empty value here
	// says exactly that rather than inventing a principal.
	CreatedBy string `json:"CreatedBy,omitempty"`

	// ts when the record was deleted
	// Format: date-time
	DeletedAt strfmt.DateTime `json:"DeletedAt,omitempty"`

	// ts when the record was last written.
	//
	// Writing a document that already exists is an UPSERT - CreateDocument with
	// an existing documentId replaces the payload - and there is no separate
	// Update rpc. Without this field an overwritten document is
	// indistinguishable from one written once, in both content and metadata, so
	// a caller cannot tell that its data was replaced or when.
	//
	// NOT a new column: ModelDocument has carried `updated_at` all along and
	// gorm has been maintaining it on every write. This only surfaces what the
	// database already records.
	//
	// Non-optional, matching _createdAt rather than _deletedAt: gorm sets
	// updated_at on create as well as on update, so every document has one. On
	// a document that has never been rewritten it equals _createdAt.
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"UpdatedAt,omitempty"`

	// updated by
	UpdatedBy string `json:"UpdatedBy,omitempty"`

	// collectionId is collection id from collection data
	CollectionID string `json:"collectionId,omitempty"`

	// dataformat
	Dataformat *APIDataFormat `json:"dataformat,omitempty"`

	// did (aka dataid) would be used to naming ${documentId} field, that field should be url safe
	DocumentID string `json:"documentId,omitempty"`

	// projectId is project id
	ProjectID string `json:"projectId,omitempty"`

	// schemaId is the schema index stored in collection
	SchemaID string `json:"schemaId,omitempty"`
}

// Validate validates this api data metadata
func (m *APIDataMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDataformat(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIDataMetadata) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("CreatedAt", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIDataMetadata) validateDeletedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.DeletedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("DeletedAt", "body", "date-time", m.DeletedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIDataMetadata) validateUpdatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("UpdatedAt", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIDataMetadata) validateDataformat(formats strfmt.Registry) error {
	if swag.IsZero(m.Dataformat) { // not required
		return nil
	}

	if m.Dataformat != nil {
		if err := m.Dataformat.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("dataformat")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("dataformat")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this api data metadata based on the context it is used
func (m *APIDataMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDataformat(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIDataMetadata) contextValidateDataformat(ctx context.Context, formats strfmt.Registry) error {

	if m.Dataformat != nil {

		if swag.IsZero(m.Dataformat) { // not required
			return nil
		}

		if err := m.Dataformat.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("dataformat")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("dataformat")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIDataMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIDataMetadata) UnmarshalBinary(b []byte) error {
	var res APIDataMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
