// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIListCollectionsResponse api list collections response
//
// swagger:model apiListCollectionsResponse
type APIListCollectionsResponse struct {

	// The project's collections, newest first.
	//
	// Deliberately the SAME message the single-collection GET returns, rather
	// than a slimmer summary type. ListByProjectID already preloads each
	// collection's latest schema and its fields - a summary type would throw
	// away data that has already been read, and would give a client two shapes
	// to parse for one resource, which is how the two drift.
	//
	// "Latest schema" is also what makes this a list of COLLECTIONS and not of
	// collection-versions: the storage query limits the preload to one schema
	// per collection.
	//
	// No pagination fields yet. Adding them later is backwards-compatible in
	// proto3; shipping page_size and page_token that nothing honours is not -
	// it tells a client the endpoint is paginated when it is not.
	Collections []*APIGetCollectionResponse `json:"collections"`
}

// Validate validates this api list collections response
func (m *APIListCollectionsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCollections(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIListCollectionsResponse) validateCollections(formats strfmt.Registry) error {
	if swag.IsZero(m.Collections) { // not required
		return nil
	}

	for i := 0; i < len(m.Collections); i++ {
		if swag.IsZero(m.Collections[i]) { // not required
			continue
		}

		if m.Collections[i] != nil {
			if err := m.Collections[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("collections" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("collections" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this api list collections response based on the context it is used
func (m *APIListCollectionsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCollections(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIListCollectionsResponse) contextValidateCollections(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Collections); i++ {

		if m.Collections[i] != nil {

			if swag.IsZero(m.Collections[i]) { // not required
				return nil
			}

			if err := m.Collections[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("collections" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("collections" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIListCollectionsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIListCollectionsResponse) UnmarshalBinary(b []byte) error {
	var res APIListCollectionsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
