// Code generated by go-swagger; DO NOT EDIT.

package collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// New creates a new collection API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

// New creates a new collection API client with basic auth credentials.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - user: user for basic authentication header.
// - password: password for basic authentication header.
func NewClientWithBasicAuth(host, basePath, scheme, user, password string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BasicAuth(user, password)
	return &Client{transport: transport, formats: strfmt.Default}
}

// New creates a new collection API client with a bearer token for authentication.
// It takes the following parameters:
// - host: http host (github.com).
// - basePath: any base path for the API client ("/v1", "/v3").
// - scheme: http scheme ("http", "https").
// - bearerToken: bearer token for Bearer authentication header.
func NewClientWithBearerToken(host, basePath, scheme, bearerToken string) ClientService {
	transport := httptransport.New(host, basePath, []string{scheme})
	transport.DefaultAuthentication = httptransport.BearerToken(bearerToken)
	return &Client{transport: transport, formats: strfmt.Default}
}

/*
Client for collection API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption may be used to customize the behavior of Client methods.
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	RestColServiceCreateCollection(params *RestColServiceCreateCollectionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RestColServiceCreateCollectionOK, error)

	RestColServiceDeleteCollection(params *RestColServiceDeleteCollectionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RestColServiceDeleteCollectionOK, error)

	RestColServiceGetCollection(params *RestColServiceGetCollectionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RestColServiceGetCollectionOK, error)

	RestColServiceListCollections(params *RestColServiceListCollectionsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RestColServiceListCollectionsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
RestColServiceCreateCollection adds collection endpoint a collection is a set of documents with scheme free
*/
func (a *Client) RestColServiceCreateCollection(params *RestColServiceCreateCollectionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RestColServiceCreateCollectionOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRestColServiceCreateCollectionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RestColService_CreateCollection",
		Method:             "POST",
		PathPattern:        "/v1/projects/{projectId}/collections",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RestColServiceCreateCollectionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RestColServiceCreateCollectionOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*RestColServiceCreateCollectionDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
RestColServiceDeleteCollection remove an individual collection and its associated doc
*/
func (a *Client) RestColServiceDeleteCollection(params *RestColServiceDeleteCollectionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RestColServiceDeleteCollectionOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRestColServiceDeleteCollectionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RestColService_DeleteCollection",
		Method:             "DELETE",
		PathPattern:        "/v1/projects/{projectId}/collections/{collectionId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RestColServiceDeleteCollectionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RestColServiceDeleteCollectionOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*RestColServiceDeleteCollectionDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
RestColServiceGetCollection retrieve an individual collection information and document keys assocaited with it
*/
func (a *Client) RestColServiceGetCollection(params *RestColServiceGetCollectionParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RestColServiceGetCollectionOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRestColServiceGetCollectionParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RestColService_GetCollection",
		Method:             "GET",
		PathPattern:        "/v1/projects/{projectId}/collections/{collectionId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RestColServiceGetCollectionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RestColServiceGetCollectionOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*RestColServiceGetCollectionDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
RestColServiceListCollections lists collections endpoint
*/
func (a *Client) RestColServiceListCollections(params *RestColServiceListCollectionsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*RestColServiceListCollectionsOK, error) {
	// NOTE: parameters are not validated before sending
	if params == nil {
		params = NewRestColServiceListCollectionsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "RestColService_ListCollections",
		Method:             "GET",
		PathPattern:        "/v1/projects/{projectId}/collections",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RestColServiceListCollectionsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}
	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}

	// only one success response has to be checked
	success, ok := result.(*RestColServiceListCollectionsOK)
	if ok {
		return success, nil
	}

	// unexpected success response.
	//
	// a default response is provided: fill this and return an error
	unexpectedSuccess := result.(*RestColServiceListCollectionsDefault)

	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
